# The GroupName here is used to identify your company or business unit that
# created this webhook.
# For example, this may be "acme.mycompany.com".
# This name will need to be referenced in each Issuer's `webhook` stanza to
# inform cert-manager of where to send ChallengePayload resources in order to
# solve the DNS01 challenge.
# This group name should be **unique**, hence using your own company's domain
# here is recommended.
groupName: acme.mycompany.com

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager




# Default values for home-assistant.

image:
  repository: ghcr.io/angelnu/cert-manager-dnsmadeeasy
  pullPolicy: IfNotPresent
  tag: v1.0.0

nodeSelector:
  # Not a multi-arch yet
  kubernetes.io/arch: amd64

args: '["--tls-cert-file=/tls/tls.crt","--tls-private-key-file=/tls/tls.key"]'

additionalVolumeMounts:
- name: certs
  mountPath: /tls
  readOnly: true


probes:
  liveness:
    enabled: true
    custom: true
    spec:
      httpGet:
        scheme: HTTPS
        path: /healthz
        port: https
  readiness:
    enabled: true
    custom: true
    spec:
      httpGet:
        scheme: HTTPS
        path: /healthz
        port: https
  startup:
    enabled: true
    custom: true
    spec:
      httpGet:
        scheme: HTTPS
        path: /healthz
        port: https
service:
  port:
    name: https
    port: 443