persistence:
  data:
    enabled: true
    size: 10M
    emptyDir:
      enabled: true
  media:
    enabled: true
    size: 10M
    emptyDir:
      enabled: true
  consume:
    enabled: true
    type: emptyDir
  export:
    enabled: true
    type: emptyDir
