#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/charts/tree/master/charts/common/values.yaml
#

image:
  repository: linuxserver/pyload
  pullPolicy: IfNotPresent
  tag: version-5f5aaf56

strategy:
  type: Recreate

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

service:
  port:
    port: 8000

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
