apiVersion: v2
appVersion: 1.0.0
description: Admision controller to change the default gateway and DNS server of PODs
name: pod-gateway
version: 1.0.2
kubeVersion: ">=1.16.0-0"
keywords:
- pod-gateway
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/pod-gateway
icon: https://pod-gateway.org/icon
sources:
- https://github.com/pod-gateway/pod-gateway-docker
maintainers:
- name: angelnu
  email: git@angelnu.com
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 2.5.0
