apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "raspberrymatic.fullname" . }}
  labels:
    {{- include "raspberrymatic.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "raspberrymatic.fullname" . }}
  selector:
    matchLabels:
      {{- include "raspberrymatic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "raspberrymatic.selectorLabels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "raspberrymatic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Values.image.tag .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range $port_type, $port_cat := .Values.service.ports -}}
          {{- range $port_name, $port_number := $port_cat }}
            - name: {{ $port_name }}
              containerPort: {{ $port_number }}
              protocol: {{ $port_type }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /usr/local
            name: ccu-volume
          - mountPath: /sys
            name: sys
      volumes:
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      - name: ccu-volume
      {{- if .Values.persistence.enabled }}
        {{- if .Values.persistence.hostPath }}
        hostPath:
          path: {{.Values.persistence.hostPath}}
          type: Directory
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "raspberrymatic.fullname" . }}{{- end }}
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
