persistentVolumes:
  # -- Local prefix for persistent volumes
  # NOTE: The default is in tempfs - you should change to a persistent place for production!!!
  hostPathPrefix: "/run/db"
  # -- Local path for the persistent volumes
  # @default: <hostPathPrefix/<release-name>
  hostPath:
  # -- persistentVolumeReclaimPolicy for the persistent volumes
  reclaimPolicy: Recycle
  accessModes:
  - ReadWriteOnce
  replicaNodes:
    - node1.example.com
    - node2.example.com
  labels: {}
  anotations: {}

dumpBackup:
  # Enable backups to a PVC
  existingClaim:
  # -- Backup schedule for postgres dumps
  schedule: "@daily"
  # -- Persistent volume claim subpath prefix for the backups
  subpathPrefix: "backup/db"
  # -- Persistent volume claim subpath for the backups
  # @default: <subpathPrefix/<release-name>
  subpath:

postgresql:
  volume:
    size: "1Gi"
  numberOfInstances: 2
  users:
    # database owner
    postgres:
    - superuser
    - createdb

  # databases: name->owner
  databases:
    postgres: postgres
  postgresql:
    version: "11"


# If you change this after creating the DB then use psql to set the password manually
superuser: postgres
# superuser_password: <my Password> - random if not set

# Dissable Deployment and Service
controllerType: ""
service:
  enabled: false
