#
## IMPORTANT NOTE
##
## This chart inherits from our common library chart. You can check the default values/options here:
## https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
##
image:
  repository: eikek0/sharry
  tag: 1.6.0
  pullPolicy: IfNotPresent

service:
  port:
    port: 9090

args:
- "/opt/sharry.conf"

ingress:
  enabled: false
  # -- Enable large file support with those annotations for nginx
  # annotations:
  #   nginx.ingress.kubernetes.io/client-body-buffer-size: "2048m"
  #   nginx.ingress.kubernetes.io/proxy-body-size: "2048m"
  #   nginx.ingress.kubernetes.io/proxy-buffering: "off"

    # -- Full list of options https://eikek.github.io/sharry/doc/configure
# @default -- see URL to default config
config: |
  sharry.restserver {
    # base-url = "https://sharry.${DOMAIN}"
    bind {
      address = "0.0.0.0"
      port = 9090
    }
    backend {
      auth {
        fixed {
          enabled = false  # set to true to enable this auth provider
          user = "admin"
          password = "admin"
          order = 10
        }
      }
    }
  }
