apiVersion: v2
version: 1.0.9
description: Creates a postgres cluster using Zalando Postgres operator
name: postgres-cluster
appVersion: 1.0.0
keywords:
- postgres
- operator
- zalando
home: https://github.com/home/charts/tree/master/charts/postgres-cluster
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Postgresql_elephant.svg/1200px-Postgresql_elephant.svg.png
sources:
- https://github.com/zalando/postgres-operator
maintainers:
- name: angelnu
  email: git@angelnu.com
dependencies:
- name: common
  repository: https://k8s-at-home.com/charts/
  version: 3.0.0