{{- if .Values.configmap.enabled | default true -}}
{{- range $namespace := append .Values.configmap.namespaces .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pod-gateway.configmap" $ | quote }}
  namespace: {{ $namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
data:
  {{- $.Values.configmap.data | toYaml | nindent 2 }}
{{- end -}}
{{- end -}}
