{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{- define "postgres-cluster.db" -}}
{{- include "common.names.fullname" .|lower -}}-postgres
{{- end -}}

{{- define "postgres-cluster.superuser_secret" -}}
{{ .Values.superuser }}.{{ include "postgres-cluster.db" . }}.credentials
{{- end -}}

{{- define "postgres-cluster.pvName" -}}
{{- include "common.names.fullname" .|lower -}}
{{- end -}}

{{- define "postgres-cluster.localPath" -}}
{{- default (printf "%s/%s" .Values.persistentVolumes.hostPathPrefix (include "common.names.fullname" .)) .Values.persistentVolumes.hostPath -}}
{{- end -}}

{{- define "postgres-cluster.backupPVCSubpath" -}}
{{- default (printf "%s/%s" .Values.dumpBackup.subpathPrefix (include "common.names.fullname" .)) .Values.dumpBackup.subpath -}}
{{- end -}}

{{/* if postgresql.volume.storageClass is not set use fullname */}}
{{- if not .Values.postgresql.volume.storageClass -}}
  {{- $_ := set .Values.postgresql.volume "storageClass" (include "common.names.fullname" .|lower ) -}}
{{- end -}}
{{- $_ := set .Values.postgresql.volume "storageClass" "bla" -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
