{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{- define "postgres-cluster.db" -}}
{{- include "common.names.fullname" .|lower -}}
{{- end -}}

{{- define "postgres-cluster.superuser_secret" -}}
{{ default (printf "%s.%s.credentials.postgresql.acid.zalan.do" .Values.superuser (include "postgres-cluster.db" .)) .Values.superuser.secret }}
{{- end -}}

{{- define "postgres-cluster.superuser" -}}
{{- default (keys .Values.postgresql.users | first ) .Values.superuser.user -}}
{{- end -}}

{{- define "postgres-cluster.superuser_password" -}}
{{- default (randAlphaNum 50) .Values.superuser.password -}}
{{- end -}}

{{- define "postgres-cluster.storageClass" -}}
{{- default (include "common.names.fullname" .|lower ) .Values.postgresql.volume.storageClass -}}
{{- end -}}

{{- define "postgres-cluster.pvName" -}}
{{- include "common.names.fullname" .|lower -}}
{{- end -}}

{{- define "postgres-cluster.localPath" -}}
{{- default (printf "%s/%s" .Values.persistentVolumes.hostPathPrefix (include "common.names.fullname" .)) .Values.persistentVolumes.hostPath -}}
{{- end -}}

{{- define "postgres-cluster.backupPVCSubpath" -}}
{{- default (printf "%s/%s" .Values.dumpBackup.subpathPrefix (include "common.names.fullname" .)) .Values.dumpBackup.subpath -}}
{{- end -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
