apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ include "postgres-cluster.db" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  {{- .Values.postgresql | toYaml | nindent 2 }}


  teamId: {{ include "common.names.fullname" . }}