{{- range $i:= untilStep 0 (int .Values.postgresql.numberOfInstances) 1 -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres-cluster.pvName" $ }}-{{ $i }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    {{- $.Values.persistentVolumes.annotations | toYaml | nindent 4 }}
  finalizers:
    - kubernetes.io/pv-protection
spec:
  storageClassName: {{ $.Values.postgresql.volume.storageClass }}
  volumeMode: Filesystem
  capacity:
    storage: "{{ $.Values.postgresql.volume.size }}"
  accessModes:
    {{- $.Values.persistentVolumes.accessModes | toYaml | nindent 4 }}
  hostPath:
  {{- if lt (len $.Values.persistentVolumes.replicaNodes) ($.Values.postgresql.numberOfInstances | int) }}
    path: {{ include "postgres-cluster.localPath" $ }}-{{ $i }}
  {{- else }}
    path: {{ include "postgres-cluster.localPath" $ }}
  {{- end }}
  #Since it is created directly this does not delete it from cluster
  persistentVolumeReclaimPolicy: "{{ $.Values.persistentVolumes.reclaimPolicy }}"
  
  {{ $e := index $.Values.persistentVolumes.replicaNodes (mod $i ($.Values.postgresql.numberOfInstances | int)) -}}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ $e }}

{{ end }}
