{{- range $i:= untilStep 0 (len $.Values.persistentVolumes.replicaNodes) 1 -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres-cluster.pvName" $ }}-{{ $i }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    {{- $.Values.persistentVolumes.annotations | toYaml | nindent 4 }}
  finalizers:
    - kubernetes.io/pv-protection
spec:
  storageClassName: {{ include "postgres-cluster.storageClass" $ }}
  volumeMode: Filesystem
  capacity:
    storage: "{{ $.Values.postgresql.volume.size }}"
  accessModes:
    {{- $.Values.persistentVolumes.accessModes | toYaml | nindent 4 }}
  hostPath:
    path: {{ include "postgres-cluster.localPath" $ }}
  #Since it is created directly this does not delete it from cluster
  persistentVolumeReclaimPolicy: "{{ $.Values.persistentVolumes.reclaimPolicy }}"
  
  {{- $e := index $.Values.persistentVolumes.replicaNodes $i }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ $e }}

{{ end }}
