{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{- define "file-cluster.glusterPath" -}}
{{- default (include "common.names.fullname" .) .Values.glusterfs.path -}}
{{- end -}}

{{- define "file-cluster.glusterfs" -}}
{{- $glusterfs := .Values.glusterfs -}}
{{- $_ := set $glusterfs "path" (include "file-cluster.glusterPath" .) -}}
{{- $glusterfs | toYaml  -}}
{{- end -}}

{{- define "file-cluster.pvcName" -}}
{{- default (include "common.names.fullname" .|lower) .Values.pvcName -}}
{{- end -}}


{{- define "file-cluster.backupPVCSubpath" -}}
{{- default (printf "%s/%s" .Values.backupPVCPrefix (include "common.names.fullname" .)) .Values.backupPVCSubpath -}}
{{- end -}}


{{/* Render the templates */}}
{{ include "common.all" . }}
