apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "file-cluster.pvcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: {{ include "common.names.fullname" . }}
  resources:
    requests:
      storage: "{{ .Values.size }}Gi"
